#!/usr/bin/env python
import traceback
import rospy
from carla_ai.ros_controller import RosController


def main():
    rospy.init_node('carla_ai_control', anonymous=True)
    role_name = rospy.get_param("~role_name", "ego_vehicle")
    controller = RosController(role_name)
    try:
        rate = rospy.Rate(5)  # ROS Rate at 20Hz
        while not rospy.is_shutdown():
            controller.tick()
            rate.sleep()
    except Exception as e:
        print('Node has been interrupted by exception', e)
        traceback.print_exc()
    finally:
        controller.destroy()


if __name__ == '__main__':
    main()
